version: '3.5'
services:
  database:
    image: mysql/mysql-server:8.0
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - /home/ubuntu/files/root/databases/${APP_DOMAIN}:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
  nginx:
    image: nginx:latest
    platform: linux/arm64/v8
    restart: unless-stopped
    volumes:
      - /home/ubuntu/files/root/websites/${APP_DOMAIN}:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      # SSL redirect requires a separate router (https://github.com/containous/traefik/issues/4688#issuecomment-477800500)
      - "traefik.http.routers.${APP_NAME}.entryPoints=web"
      - "traefik.http.routers.${APP_NAME}.rule=host(`${APP_DOMAIN}`)"
      - "traefik.http.middlewares.${APP_NAME}-redirect.redirectScheme.scheme=https"
      - "traefik.http.middlewares.${APP_NAME}-redirect.redirectScheme.permanent=true"
      - "traefik.http.routers.${APP_NAME}.middlewares=${APP_NAME}-redirect"
      # SSL endpoint
      - "traefik.http.routers.${APP_NAME}-https.entryPoints=websecure"
      - "traefik.http.routers.${APP_NAME}-https.rule=host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}-https.tls=true"
      - "traefik.http.routers.${APP_NAME}-https.tls.certResolver=production"
      - "traefik.http.routers.${APP_NAME}-https.service=${APP_NAME}-https"
      - "traefik.http.services.${APP_NAME}-https.loadBalancer.server.port=80"
    networks:
      - traefik

networks:
  traefik:
    name: traefik_default
